
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.customwcfrestservice.WSASpDatosIesResult;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ILoginService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.customwcfrestservice.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface ILoginService {


    /**
     * 
     * @param userName
     * @param password
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "Login", action = "http://tempuri.org/ILoginService/Login")
    @WebResult(name = "LoginResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Login", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginResponse")
    public Boolean login(
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param userName
     * @param password
     * @return
     *     returns org.datacontract.schemas._2004._07.customwcfrestservice.WSASpDatosIesResult
     */
    @WebMethod(operationName = "InfoInstitucionXML", action = "http://tempuri.org/ILoginService/InfoInstitucionXML")
    @WebResult(name = "InfoInstitucionXMLResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InfoInstitucionXML", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InfoInstitucionXML")
    @ResponseWrapper(localName = "InfoInstitucionXMLResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InfoInstitucionXMLResponse")
    public WSASpDatosIesResult infoInstitucionXML(
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param userName
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InfoInstitucionJson", action = "http://tempuri.org/ILoginService/InfoInstitucionJson")
    @WebResult(name = "InfoInstitucionJsonResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InfoInstitucionJson", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InfoInstitucionJson")
    @ResponseWrapper(localName = "InfoInstitucionJsonResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InfoInstitucionJsonResponse")
    public String infoInstitucionJson(
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

}
